# Generated by Django 6.0.1 on 2026-02-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='maps/', verbose_name='Изображение')),
                ('width', models.IntegerField(verbose_name='Ширина (пикс)')),
                ('height', models.IntegerField(verbose_name='Высота (пикс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название слоя')),
                ('color', models.CharField(default='#3388ff', max_length=7, verbose_name='Цвет')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='maps.gamemap')),
            ],
            options={
                'verbose_name': 'Слой',
                'verbose_name_plural': 'Слои',
            },
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('marker', 'Маркер'), ('polyline', 'Линия'), ('polygon', 'Зона'), ('rectangle', 'Прямоугольник'), ('circle', 'Круг')], max_length=20, verbose_name='Тип')),
                ('coordinates', models.JSONField(verbose_name='Координаты')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='Свойства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('map_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_objects', to='maps.maplayer')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
