# Generated by Django 6.0.1 on 2026-02-02 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapobject',
            name='map_layer',
        ),
        migrations.AlterModelOptions(
            name='gamemap',
            options={},
        ),
        migrations.RemoveField(
            model_name='gamemap',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gamemap',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='image',
            field=models.ImageField(upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='width',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='MapDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('marker', 'Маркер'), ('polyline', 'Линия'), ('polygon', 'Область'), ('rectangle', 'Прямоугольник'), ('circle', 'Круг'), ('text', 'Текст')], max_length=20)),
                ('color', models.CharField(default='#ff0000', max_length=7)),
                ('coordinates', models.JSONField()),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='maps.gamemap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MapLayer',
        ),
        migrations.DeleteModel(
            name='MapObject',
        ),
    ]
