# Generated by Django 6.0.1 on 2026-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_mapobject_map_layer_alter_gamemap_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemap',
            name='mode',
            field=models.CharField(choices=[('random', 'Случайный бой'), ('attack_defense', 'Атака/Оборона'), ('encounter', 'Встречный бой'), ('assault', 'Штурм'), ('grand_battle', 'Генеральное сражение'), ('clash', 'Столкновение'), ('other', 'Другой')], default='random', max_length=20, verbose_name='Режим игры'),
        ),
    ]
