# Generated by Django 6.0.1 on 2026-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_gamemap_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='height',
            field=models.IntegerField(default=1000, editable=False),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='width',
            field=models.IntegerField(default=1000, editable=False),
        ),
    ]
