# Generated by Django 6.0.1 on 2026-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_alter_gamemap_height_alter_gamemap_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='height',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='mode',
            field=models.CharField(choices=[('random', 'Случайный бой'), ('attack_defense', 'Атака/Оборона'), ('encounter', 'Встречный бой'), ('assault', 'Штурм'), ('grand_battle', 'Генеральное сражение'), ('clash', 'Столкновение')], default='random', max_length=20, verbose_name='Режим игры'),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='width',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
