# Generated by Django 6.0.1 on 2026-03-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_gamemap_height_alter_gamemap_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='width',
            field=models.IntegerField(default=1000),
        ),
    ]
