# Generated by Django 6.0.1 on 2026-03-05 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='Ник в игре')),
                ('discord_nick', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord')),
                ('average_damage', models.IntegerField(default=0, verbose_name='Средний урон')),
                ('commander_notes', models.TextField(blank=True, verbose_name='Заметки командира')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в рейтинге')),
                ('total_battles', models.IntegerField(default=0, verbose_name='Всего боев')),
                ('wins', models.IntegerField(default=0, verbose_name='Побед')),
                ('losses', models.IntegerField(default=0, verbose_name='Поражений')),
                ('position_history', models.JSONField(blank=True, default=list, verbose_name='История позиций')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный игрок')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-average_damage'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название танка')),
                ('tier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень')),
                ('nation', models.CharField(max_length=50, verbose_name='Нация')),
            ],
            options={
                'verbose_name': 'Танк',
                'verbose_name_plural': 'Танки',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DuelSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_wins', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Побед игрока 1')),
                ('player2_wins', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Побед игрока 2')),
                ('player1_avg_damage', models.IntegerField(default=0, verbose_name='Средний урон игрока 1')),
                ('player2_avg_damage', models.IntegerField(default=0, verbose_name='Средний урон игрока 2')),
                ('player1_damage_change', models.IntegerField(default=0, verbose_name='Изменение среднего урона P1')),
                ('player2_damage_change', models.IntegerField(default=0, verbose_name='Изменение среднего урона P2')),
                ('position_swapped', models.BooleanField(default=False, verbose_name='Позиции поменялись')),
                ('old_position_player1', models.IntegerField(blank=True, null=True, verbose_name='Старая позиция P1')),
                ('old_position_player2', models.IntegerField(blank=True, null=True, verbose_name='Старая позиция P2')),
                ('session_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сессии')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_player1', to='clan.player', verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_player2', to='clan.player', verbose_name='Игрок 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sessions', to='clan.player', verbose_name='Победитель сессии')),
                ('tank1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_tank1', to='clan.tank', verbose_name='Танк игрока 1')),
                ('tank2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_tank2', to='clan.tank', verbose_name='Танк игрока 2')),
            ],
            options={
                'verbose_name': 'Дуэльная сессия',
                'verbose_name_plural': 'Дуэльные сессии',
                'ordering': ['-session_date'],
            },
        ),
    ]
