# Generated by Django 6.0.1 on 2026-03-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duelsession',
            name='tank1',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='tank2',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='old_position_player1',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='old_position_player2',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player1_avg_damage',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player1_damage_change',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player1_wins',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player2_avg_damage',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player2_damage_change',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player2_wins',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='position_swapped',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wins',
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player1_new_damage',
            field=models.IntegerField(default=0, verbose_name='Новый средний урон игрока 1'),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player2_new_damage',
            field=models.IntegerField(default=0, verbose_name='Новый средний урон игрока 2'),
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
