# Generated by Django 6.0.1 on 2026-03-05 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0002_remove_duelsession_tank1_remove_duelsession_tank2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelsession',
            name='new_position_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='new_position_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='old_position_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='old_position_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player1_battle_damage',
            field=models.IntegerField(default=0, verbose_name='Урон игрока 1'),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player1_tank',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Танк игрока 1'),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player2_battle_damage',
            field=models.IntegerField(default=0, verbose_name='Урон игрока 2'),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player2_tank',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Танк игрока 2'),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='position_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins_as_winner', to='clan.player', verbose_name='Победитель'),
        ),
    ]
