# Generated by Django 6.0.1 on 2026-03-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_duelsession_new_position_player1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duelsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player1_new_damage',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player1_tank',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player2_new_damage',
        ),
        migrations.RemoveField(
            model_name='duelsession',
            name='player2_tank',
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player1_damage_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='player2_damage_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='tank1',
            field=models.CharField(default='Не указан', max_length=100),
        ),
        migrations.AddField(
            model_name='duelsession',
            name='tank2',
            field=models.CharField(default='Не указан', max_length=100),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_player1', to='clan.player'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player1_battle_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_player2', to='clan.player'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player2_battle_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='session_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='clan.player'),
        ),
    ]
