# Generated by Django 6.0.1 on 2026-03-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0004_alter_duelsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duelsession',
            options={'ordering': ['-session_date'], 'verbose_name': 'Дуэльная сессия', 'verbose_name_plural': 'Дуэльные сессии'},
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='Поражений'),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Побед'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='new_position_player1',
            field=models.IntegerField(default=0, verbose_name='Позиция P1 после'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='new_position_player2',
            field=models.IntegerField(default=0, verbose_name='Позиция P2 после'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='old_position_player1',
            field=models.IntegerField(default=0, verbose_name='Позиция P1 до'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='old_position_player2',
            field=models.IntegerField(default=0, verbose_name='Позиция P2 до'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player1_battle_damage',
            field=models.IntegerField(default=0, verbose_name='Урон игрока 1'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player1_damage_change',
            field=models.IntegerField(default=0, verbose_name='Изменение урона P1'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player2_battle_damage',
            field=models.IntegerField(default=0, verbose_name='Урон игрока 2'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='player2_damage_change',
            field=models.IntegerField(default=0, verbose_name='Изменение урона P2'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='position_changed',
            field=models.BooleanField(default=False, verbose_name='Позиции изменились'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='session_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сессии'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='tank1',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Танк игрока 1'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='tank2',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Танк игрока 2'),
        ),
        migrations.AlterField(
            model_name='duelsession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sessions', to='clan.player'),
        ),
    ]
